name: star_book
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ^3.10.1

# Automatically upgrade your dependencies to the
# latest versions `flutter pub upgrade --major-versions`.
# See dependencies have newer versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed: ^2.2.1
  freezed_annotation: ^2.2.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  flutter_bloc: ^8.1.1
  kiwi: ^4.0.3
  shared_preferences: ^2.1.1
  
  # Non Technical Dependencies
  logger: ^1.1.0
  syncfusion_flutter_charts: ^21.2.6
  intl: ^0.18.0
  go_router: ^7.1.1
  path_provider: ^2.0.12
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.0.0
  url_launcher: ^6.1.11
  package_info_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  flutter_lints: ^2.0.0
  isar_generator: ^3.0.5
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  image_path: "assets/icon.png"


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/icons/
     - assets/images/

  fonts:
     - family: Inter
       fonts:
         - asset: assets/fonts/Inter-Bold.ttf
           weight: 700
         - asset: assets/fonts/Inter-Medium.ttf
           weight: 500
         - asset: assets/fonts/Inter-Regular.ttf
           weight: 400
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

